### ISSUE TITLE
Make app id available to client for display in app

### ISSUE THREAD

**Issue by arieljake** [driftyco/ionic-plugins-deploy#11]
For debugging purposes, it would be handy to receive the metadata about the version of the app that has been deployed, most specifically the ID, so that it can be displayed in an About dialog.

**Comment by ericb** [comment]
With the latest ionic-service-deploy and ionic-plugin-deploy you can run:

```javascript
$ionicDeploy.info().then(function(result) { console.log(result); }, function() {}, function() {});
```

Should return something such as:

```json
{
    "deploy_uuid": "11ec611e2a4e11e5b61a7831c1d5e1b8",
    "binary_version": "0.0.1"
}
```
