### ISSUE TITLE
Plugin crashes when opening the app in offline mode

### ISSUE THREAD

**Issue by ghaiat** [driftyco/ionic-plugins-deploy#14]
Hello, when opening my app in offline mode (no internet connection), the plugin crashes and my app automatically crashes.
here is a screenshot of xcode

https://www.dropbox.com/s/4swrq5lee7tlk8t/Screenshot%202015-06-18%2014.27.08.png?dl=0

**Comment by ericb** [comment]
I will get this cleaned up. Thanks @ghaiat
