### ISSUE TITLE
app.ionic.io does not allow you to 'unset' equivalent versions

### ISSUE THREAD

**Issue by Deminetix** [driftyco/ionic-plugins-deploy#22]
Steps to produce:

- On `app.ionic.io` enter equivalent values for a version and, hit save
- values are updated
- edit version again and clear inputs of equivalent values, hit save
- request sends empty strings instead of null, and the response hasn't removed the original values

I copied the cURL request and tried using null instead of empty strings but that didn't fix it either. I assume it is a backend issue

**Comment by ericb** [comment]
Confirmed. I'll get this fixed up. Thanks @Deminetix
