### ISSUE TITLE
Android compile error

### ISSUE THREAD

**Issue by rosterloh** [driftyco/ionic-plugins-deploy#3]
```
IonicDeploy.java:156: error: method loadUrlIntoView in interface CordovaWebView cannot be applied to given types;
            webView.loadUrlIntoView(versionDir.toURI() + "index.html");
                   ^
  required: String,boolean
  found: String
  reason: actual and formal argument lists differ in length
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
1 error
```

Ionic-cli: 1.4.0-beta.6
Cordova: 5.0.0
Node: 0.12.2

**Comment by rosterloh** [comment]
It seems they've add another parameter. 
```java
void loadUrlIntoView(String url, boolean recreatePlugins);
```
https://github.com/apache/cordova-android/blob/master/framework/src/org/apache/cordova/CordovaWebView.java

**Comment by nikmartin** [comment]
More specifically, the implementation:https://github.com/apache/cordova-android/blob/0f73884c8d93d071aa763079825b576ca493bf96/framework/src/org/apache/cordova/CordovaWebViewImpl.java#L126

**Comment by ericb** [comment]
With the latest merge the new deploy plugin is available via npm if you're on Cordova 5.x
