### ISSUE TITLE
Crash on Startup in Emulator

### ISSUE THREAD

**Issue by RangerRick** [driftyco/ionic-plugins-deploy#5]
When I run `ionic emulate -slc ios` after adding Ionic Deploy to my project, I get this crash: http://pastebin.com/Dy17L62W

I've tried an `ionic state reset` just to make sure my project was clean, but it still occurs.  The com.ionic.update plugin version is 0.0.5, the default after following the instructions on docs.ionic.io.

**Comment by RangerRick** [comment]
Additional info: I noticed that while I had done an `ionic upload`, I had not actually gone to the deploy UI on apps.ionic.io to deploy it officially so there were 0 deployed versions of my app. However, even after doing so, it still crashes on me in the same place (CFURLCopyAbsoluteURL).

**Comment by ericb** [comment]
@RangerRick The plugin has been updated quite a bit since this was opened. Can you verify if this is still an issue? I don't think it will be but i'll leave this open for now just in case.

**Comment by RangerRick** [comment]
I'm still seeing a crash in `ionic emulate` on startup with 0.1.5: https://gist.github.com/RangerRick/646963e65fedb7c9d187

I just did an "ionic state reset" and "bower install" just to make sure everything was up-to-date and it appears everything is as it should be.

**Comment by ericb** [comment]
@RangerRick The plugin id has changed to com.ionic.deploy -- Do you still have the older com.ionic.update around? You can list the plugins with `ionic plugin list`

**Comment by RangerRick** [comment]
Aha!  Yup, mine was still pointing at com.ionic.update instead.  Looks like that fixed it.  Now to figure out how to upload my minified code rather than the raw www directory when I do `ionic upload`.  :)
