### ISSUE TITLE
Updates do not persist on app restarts

### ISSUE THREAD

**Issue by m0rganic** [driftyco/ionic-plugins-deploy#6]
I'm testing out the deploy service using the  [ionic-starter-deploy](https://github.com/driftyco/ionic-starter-deploy) example.

The behavior I've observed on both iOS and Android is that the app is able to recognize, receive and apply the update from ionic deploy service *but* the update does not "stick" and after killing the app and restarting the original version is active again.

```
$ ionic info

Your system information:

OS: Mac OS X Yosemite
Node Version: v0.10.38
Cordova CLI: 5.0.0
Ionic Version: 1.0.0-rc.5
Ionic CLI Version: 1.3.22
Xcode version: Xcode 6.3.1 Build version 6D1002
ios-sim version: 3.1.1
ios-deploy version: 1.5.0
```

**Comment by PaperMonster** [comment]
Cordova CLI: 4.3.0
Gulp version:  CLI version 3.8.10
Gulp local:   Local version 3.8.10
Ionic Version: 1.0.0-rc.3
Ionic CLI Version: 1.4.5
Ionic App Lib Version: 0.0.22
ios-deploy version: 1.4.0
ios-sim version: 3.1.1
OS: Mac OS X Yosemite
Node Version: v0.10.33
Xcode version: Xcode 6.3.1 Build version 6D1002

**Comment by ericb** [comment]
The latest version (0.1.5 as of writing this) should have resolved this issue. You'll need to update your ionic-service-core, ionic-service-deploy, and ionic-plugin-deploy to work correctly. You'll also need to test with newly uploaded versions once you update those components/plugins.
